import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'routes/app_pages.dart';
import 'firebase_options.dart'; // This will be generated by the user
import 'controllers/auth_controller.dart';
import 'theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // Note: User needs to generate firebase_options.dart using `flutterfire configure`
  // We wrap this in a try-catch or check to avoid crashing if not configured yet,
  // but for production code we expect it to be there.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase initialization failed: $e");
    // For development without firebase_options.dart, we might want to show a warning
    // or just proceed if we are mocking auth.
  }

  // Initialize AuthController globally
  Get.put(AuthController());

  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter GetX App',
      debugShowCheckedModeBanner: false,
      
      // Theme Configuration
      theme: AppTheme.darkTheme,
      
      // Routing
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      
      // Default transition
      defaultTransition: Transition.cupertino,
    );
  }
}
